# Generated by Django 4.2.3 on 2023-07-09 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='آدرس دسته')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش دادن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان شرکت')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('about', models.TextField(blank=True, null=True, verbose_name='درباره شرکت')),
                ('manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='مدیرعامل شرکت')),
                ('manager_photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر مدیرعامل')),
                ('slider', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='بنر شرکت')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video')),
                ('catalog', models.FileField(blank=True, null=True, upload_to='')),
                ('catalog_cover', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='جلد کاتالوگ')),
                ('telephone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن شرکت')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='وبسایت')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(blank=True, max_length=200, null=True, verbose_name='موبایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='')),
                ('show_baner', models.BooleanField(verbose_name='نمایش بنر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='category', to='companies.companycategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
    ]
