# Generated by Django 4.2.3 on 2023-07-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان شرکت')),
                ('about', models.TextField(verbose_name='درباره شرکت')),
                ('manager', models.CharField(max_length=200, null=True, verbose_name='مدیرعامل شرکت')),
                ('manager_photo', models.ImageField(upload_to='images', verbose_name='تصویر مدیرعامل')),
                ('slider', models.ImageField(upload_to='images', verbose_name='بنر شرکت')),
                ('video', models.FileField(upload_to='media/video')),
                ('catalog', models.FileField(upload_to='')),
                ('catalog_cover', models.ImageField(upload_to='images', verbose_name='جلد کاتالوگ')),
                ('telephone', models.CharField(max_length=200, verbose_name='تلفن شرکت')),
                ('fax', models.CharField(max_length=200, verbose_name='فکس')),
                ('website', models.CharField(max_length=200, verbose_name='وبسایت')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=200, verbose_name='موبایل')),
                ('address', models.TextField(verbose_name='موبایل')),
                ('certificates', models.FileField(upload_to='')),
                ('show_baner', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
