# Generated by Django 4.2.3 on 2023-07-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(null=True, verbose_name='درباره شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='company',
            name='catalog',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='catalog_cover',
            field=models.ImageField(null=True, upload_to='images', verbose_name='جلد کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(max_length=200, null=True, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager_photo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='تصویر مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(max_length=200, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='show_baner',
            field=models.BooleanField(verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slider',
            field=models.ImageField(null=True, upload_to='images', verbose_name='بنر شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(max_length=200, null=True, verbose_name='تلفن شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='video',
            field=models.FileField(null=True, upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=200, null=True, verbose_name='وبسایت'),
        ),
    ]
