# Generated by Django 4.2.3 on 2023-07-09 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی محصول')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='آدرس دسته بندی محصول')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش دادن')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='catalog',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='کاتالوگ شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='catalog_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='جلد کاتالوگ شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='slug')),
                ('model', models.CharField(max_length=200, verbose_name='مدل محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه محصول')),
                ('gallery', models.FileField(upload_to='')),
                ('catalog', models.FileField(blank=True, null=True, upload_to='', verbose_name='کاتالوگ محصول')),
                ('catalog_cover', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='جلد کاتالوگ محصول')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/video')),
                ('show_sertificates', models.BooleanField(verbose_name='نمایش گواهی نامه های شرکت')),
                ('first_feature', models.CharField(max_length=200, verbose_name='ویژگی اول محصول')),
                ('second_feature', models.CharField(max_length=200, verbose_name='ویژگی دوم محصول')),
                ('third_feature', models.CharField(max_length=200, verbose_name='ویژگی سوم محصول')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='product_category', to='companies.productcategory', verbose_name='دسته بندی محصول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.company', verbose_name='نام شرکت')),
            ],
        ),
    ]
