# Generated by Django 4.2.3 on 2023-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_about_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='certificates',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='show_baner',
            field=models.BooleanField(verbose_name='نمایش بنر'),
        ),
    ]
