# Generated by Django 4.2.3 on 2023-07-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_productcategory_alter_company_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company', to='companies.company', verbose_name='نام شرکت'),
        ),
    ]
