# Generated by Django 4.2.3 on 2023-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_certificates_alter_company_show_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='catalog',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='catalog_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='جلد کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مدیرعامل شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slider',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='بنر شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وبسایت'),
        ),
    ]
