# Generated by Django 4.2.3 on 2023-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_product_first_feature_alter_product_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مدل محصول'),
        ),
    ]
