# Generated by Django 4.2.3 on 2023-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='companies.productcategory', verbose_name='دسته بندی محصول'),
        ),
    ]
